### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by L-JuneF** [zhongyu1998/PG-GNN#1]
In COLLAB dataset, the first line is number of all graphs, and the second line is a graph and its labels.
I want konw the what does the next line mean. 
and in you code             
          for j in range(n):
                g.add_node(j)
                row = f.readline().strip().split()
                tmp = int(row[1]) + 2
                if tmp == len(row):
                    row = [int(w) for w in row]
                    attr = None
                else:
                    row, attr = [int(w) for w in row[:tmp]], np.array([float(w) for w in row[tmp:]])
                if not row[0] in feat_dict:
                    mapped = len(feat_dict)
                    feat_dict[row[0]] = mapped
                node_tags.append(feat_dict[row[0]])
why would you do that tmp = int(row[1])  +2

**Comment by zhongyu1998** [comment]
Thank you for your interest in our code. This line of code is sourced from GIN (Line 54, https://github.com/weihua916/powerful-gnns/blob/master/util.py). Since the function 'load_data' is commonly used for many datasets in TUDataset, some of which have node attributes while others do not, we determine whether node attributes are available based on whether 'tmp' is equal to 'len(row)' (Lines 54-59). In most lines of each dataset, each line represents a node, column 1 represents the node feature of the current node, column 2 represents the number of neighbors of the current node, columns 3 to 'tmp' represent the neighbors of the current node, and after the 'tmp' column represents the node attributes (if any).

**Comment by L-JuneF** [comment]
ok，理解了，感谢解答；所以所有的节点的特征都是0吗？用节点在图里面的结构特征作为input？

**Comment by zhongyu1998** [comment]
The original datasets provide the atomic categorical label for each node in the bioinformatics graphs (e.g., PROTEINS and NCI1). However, node features are not provided for social networks (e.g., IMDB-B, IMDB-M, and COLLAB) and are thus set to zeros. As described in the main text (Section 4.2), "We follow Xu et al. (2019) to create the input features for each node. More specifically, the input node features of bioinformatics graphs are categorical node labels, and the input node features of social networks are node degrees. All the input features are encoded in a one-hot manner."
